---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tv9x6755/tv9web
    - /bin/cp -r . $DEPLOYPATH
    - cd $DEPLOYPATH
    - composer install --no-dev --optimize-autoloader
    - npm ci --omit=dev && npm run build
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan storage:link
